version: "3.8"
services:
  frontend:
    container_name: twitter-clone-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app" # ローカルのソースコードをコンテナの/appディレクトリにマウント
      - "/app/node_modules" # node_modulesディレクトリを匿名ボリュームとして扱い、オーバーライドを防ぐ
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # ファイルシステムのイベントが正しく伝達されるように設定
    restart: unless-stopped
